### ISSUE TITLE
[Resource]: European Atlas of the Seas

### ISSUE THREAD

**Issue by tim-collart** [schmidtocean/awesome-ocean-data-resources#3]
### Resource Name

European Atlas of the Seas

### More information

https://ec.europa.eu/maritimeaffairs/atlas/maritime_atlas/

### Data Steward Orgainzation Type

Government

### Data Steward Orgainzation Name

European Commission Directorate General for Maritime Affairs and Fisheries

**Comment by CorinneBassin-SOI** [comment]
done, thanks!
