### ISSUE TITLE
[Resource]: Please update the EMODnet listing to the new domain

### ISSUE THREAD

**Issue by tim-collart** [schmidtocean/awesome-ocean-data-resources#4]
### Resource Name

EMODnet

### More information

https://emodnet.ec.europa.eu/

### Data Steward Orgainzation Type

Government

### Data Steward Orgainzation Name

European Commission Directorate General for Maritime Affairs and Fisheries

**Comment by CorinneBassin-SOI** [comment]
Done, thanks
